# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python

python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"

before_script:
  # add ppa with more recent scipy version
  - sudo add-apt-repository ppa:pylab/stable  -y
  - sudo apt-get update -qq
  - sudo apt-get install -y python-sphinx python-nose python-numpy python-scipy
  - sudo apt-get install -y python3-sphinx python3-nose python3-numpy python3-scipy
  - git config --global user.email "per.andreas.brodtkorb@gmail.com"
  - git config --global user.name "pbrod"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
